export const REGIONAIS = [
  "Açailândia",
  "Bacabal",
  "Balsas",
  "Barra do Corda",
  "Caxias",
  "Chapadinha",
  "Codó",
  "Imperatriz",
  "Itapecuru Mirim",
  "Pedreiras",
  "Pinheiro",
  "Presidente Dutra",
  "Rosário",
  "Santa Inês",
  "São João dos Patos",
  "São Luís",
  "Timon",
  "Viana",
  "Zé Doca",
];

export const ESCOLAS_POR_REGIONAL: { [key: string]: string[] } = {
  "São Luís": [
    "U.I. ESTADO DO AMAZONAS",
    "C.E. SAO CRISTOVAO",
    "C.E. CIDADE DE SAO LUIS",
    "C.E. DESEMBARGADOR SARNEY COSTA",
    "U.I. PROFESSORA CAMELIA VIVEIROS",
  ],
  "Imperatriz": [
    "C.E. GOVERNADOR EDISON LOBAO",
    "C.E. DOUTOR ADEMAR AZEVEDO",
    "C.E. GRAÇA ARANHA",
    "C.E. COELHO NETO",
  ],
  "Açailândia": ["ESCOLA MODELO 1", "ESCOLA MODELO 2"],
  "Bacabal": ["ESCOLA MODELO 3", "ESCOLA MODELO 4"],
  "Balsas": ["ESCOLA MODELO 5", "ESCOLA MODELO 6"],
  "Barra do Corda": ["ESCOLA MODELO 7", "ESCOLA MODELO 8"],
  "Caxias": ["ESCOLA MODELO 9", "ESCOLA MODELO 10"],
  "Chapadinha": ["ESCOLA MODELO 11", "ESCOLA MODELO 12"],
  "Codó": ["ESCOLA MODELO 13", "ESCOLA MODELO 14"],
  "Itapecuru Mirim": ["ESCOLA MODELO 15", "ESCOLA MODELO 16"],
  "Pedreiras": ["ESCOLA MODELO 17", "ESCOLA MODELO 18"],
  "Pinheiro": ["ESCOLA MODELO 19", "ESCOLA MODELO 20"],
  "Presidente Dutra": ["ESCOLA MODELO 21", "ESCOLA MODELO 22"],
  "Rosário": ["ESCOLA MODELO 23", "ESCOLA MODELO 24"],
  "Santa Inês": ["ESCOLA MODELO 25", "ESCOLA MODELO 26"],
  "São João dos Patos": ["ESCOLA MODELO 27", "ESCOLA MODELO 28"],
  "Timon": ["ESCOLA MODELO 29", "ESCOLA MODELO 30"],
  "Viana": ["ESCOLA MODELO 31", "ESCOLA MODELO 32"],
  "Zé Doca": ["ESCOLA MODELO 33", "ESCOLA MODELO 34"],
};
