-- ============================================================================
--  escolas.id passa a ser gerado pelo banco
-- ============================================================================
--  Sintoma: cadastrar uma unidade pela tela sempre falhou com
--      null value in column "id" of relation "escolas" violates not-null constraint
--
--  Causa: a coluna e' `bigint not null` SEM default e SEM sequence. As 486
--  linhas existentes vieram com id explicito na carga inicial (planilha de
--  unidades da SEDUC), entao a ausencia de default nunca incomodou ninguem --
--  ate alguem tentar criar uma unidade nova, quando o INSERT nao manda id e o
--  banco nao tem de onde tirar um.
--
--  `by default` (e nao `always`) de proposito: importacoes e correcoes de dados
--  precisam continuar podendo gravar um id escolhido a mao.
-- ============================================================================

alter table public.escolas
    alter column id add generated by default as identity;

-- A sequence recem-criada comeca em 1, e os ids em uso vao ate 1486: sem este
-- ajuste as primeiras 1486 insercoes colidiriam com a chave primaria.
select setval(
    pg_get_serial_sequence('public.escolas', 'id'),
    (select coalesce(max(id), 0) from public.escolas),
    true
);

-- createEscola() ja traduz o erro 23505 para "Ja existe uma escola com este
-- INEP", mas nao existia restricao capaz de disparar esse codigo: ate agora
-- dava para cadastrar a mesma unidade duas vezes. Os dados atuais nao tem
-- nenhum INEP nulo nem repetido, entao o indice sobe sem precisar de limpeza.
create unique index if not exists escolas_inep_key
    on public.escolas (inep);
